FROM alpine:3

LABEL author ="Arlodel"
LABEL company="ArloDel" website="https://arlodel.com" email="contact@arlodel.com"

RUN mkdir hello
RUN echo "Hello, World!" > hello/world.txt

CMD cat hello/world.txt